# Overrides for certify in QA (solo propiedades con URL específicas del ambiente)
mosip.certify.domain.url=https://certify.staging.inji-reniec.com
mosip.certify.identifier=https://certify.staging.inji-reniec.com
mosip.certify.authn.issuer-uri=https://idaas2.reniec.gob.pe/service
mosip.certify.authn.jwk-set-uri=https://idaas2.reniec.gob.pe/service/jwks
mosip.certify.authorization.url=https://idaas2.reniec.gob.pe/service
mosip.certify.authn.allowed-audiences={'https://idaas2.reniec.gob.pe/service/token', 'http://localhost:8090/v1/certify/issuance/credential','https://certify.staging.inji-reniec.com/v1/certify/issuance/credential','https://certify.staging.inji-reniec.com','certify-client', 'wallet-demo', 'wallet-demo-client', 'aud1', 'aud2', 'account' }
mosip.certify.data-provider-plugin.did-url=did:web:emmanuelacostaiugo.github.io:DID:test
mosip.certify.issuer.pub.key=did:web:emmanuelacostaiugo.github.io:DID:test#key-0
mosip.certify.issuer.uri=did:web:emmanuelacostaiugo.github.io:DID:test
mosip.kernel.keymanager.hsm.config-path=/config/softhsm-application.conf
certify.data-provider-plugin.restapi.document-number-key=document_number
certify.data-provider-plugin.restapi.filiation-document-number-key=binding_message
mosip.certify.data-provider-plugin.restapi.context-path.dnid=ws-dni-dnid
mosip.certify.data-provider-plugin.restapi.obtener-datos-path=/ObtenerDatosDNId
mosip.certify.data-provider-plugin.restapi.base-url=https://dniddesa.reniec.gob.pe
