# Overrides for certify in prod (solo propiedades con URL específicas del ambiente)
mosip.certify.domain.url=https://certify.prod.inji-reniec.com
mosip.certify.identifier=https://certify.prod.inji-reniec.com
mosip.certify.authn.issuer-uri=https://idaas2.reniec.gob.pe/service
mosip.certify.authn.jwk-set-uri=https://idaas2.reniec.gob.pe/service/jwks
mosip.certify.authn.allowed-audiences={'https://certify.prod.inji-reniec.com','http://certify:8090/v1/certify/issuance/credential', "https://keycloak.iugolabs.com/realms/inji-poc/protocol/openid-connect/token", 'https://idaas2.reniec.gob.pe/service/token', 'http://localhost:8090/v1/certify/issuance/credential', 'https://certify.prod.inji-reniec.com/v1/certify/issuance/credential', 'certify-client', 'wallet-demo', 'wallet-demo-client', 'aud1', 'aud2', 'account' }
mosip.certify.authorization.url=https://keycloak.iugolabs.com/realms/inji-poc
mosip.certify.data-provider-plugin.did-url=did:web:emmanuelacostaiugo.github.io:DID:prod
mosip.certify.issuer.pub.key=did:web:emmanuelacostaiugo.github.io:DID:prod#key-0
mosip.certify.issuer.uri=did:web:emmanuelacostaiugo.github.io:DID:prod
mosip.kernel.keymanager.hsm.config-path=/config/cloudhsm-application.conf
mosip.certify.data-provider-plugin.restapi.base-url=https://dnidigidesa.reniec.gob.pe:7003
