## ------------------------------------------- Mock ID Integration properties ------------------------------------------------------------
mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.audit-plugin=LoggerAuditService


## ------------------------------------------- Mock ID plugin related properties ------------------------------------------------------------
mosip.certify.cache.security.algorithm-name=AES/ECB/PKCS5Padding
mosip.certify.cache.secure.individual-id=false
mosip.certify.cache.store.individual-id=true
mosip.certify.cnonce-expire-seconds=300
## DataProvider plugin specific changes
mosip.certify.issuer=CertifyIssuer
mosip.certify.vcformat.vc.expiry=true
# optional field to specify VC signature algo for CertifyIssuer, defaults to Ed25519Signature2020
# other option: [RsaSignature2018]
mosip.certify.issuer.vc-sign-algo=Ed25519Signature2020

mosip.certify.issuer.svg.template.id=5b9c2a12-810a-7388-2dc8-13ee7ad88bac
#mosip.certify.integration.data-provider-plugin=RestApiDataProviderPlugin
# Mimoto -- INJIMOB-2446
mosip.certify.svg-templates=${spring_config_url_env}/${spring.application.name}/${active_profile_env}/${spring_config_label_env}/mosipid-svg-template.json

#to be updated to GitHub pages url when one is running locally, otherwise it can be replaced with the certify service did url


mosip.certify.plugin-mode=DataProvider
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/
mosip.certify.integration.data-provider-plugin=RestApiDataProviderPlugin
mosip.certify.database.name=inji_certify
mosip.certify.status-list.signature-crypto-suite=Ed25519Signature2020
## CSV specific config
logging.level.io.mosip.certify.services.CertifyIssuanceServiceImpl=DEBUG
logging.level.root=INFO
logging.level.io.mosip.certify=DEBUG
mosip.certify.data-provider-plugin.rendering-template-id=
mosip.certify.credential-config.issuer.display={\
  {\
    'name': 'DNI Peruano Issuer',\
    'locale': 'en'\
  }\
}
mosip.certify.data-provider-plugin.restapi.scope-endpoint-mapping={ 'dni_filiacion':'dni_filiacion', 'dni':'dni', 'acta_matrimonio':'acta_matrimonio', 'acta_nacimiento':'acta_nacimiento', 'acta_nacimiento_filiacion':'acta_nacimiento_filiacion', 'land_registry_vc_ldp':'dni' }

reniec.certify.data-provider-plugin.restapi.scope-perfilconsulta-mapping={\
  'acta_nacimiento': 'ACTA_NACIMIENTO',\
  'dnimayor_con_hijos': 'DNID_MAYOREDAD_CONHIJOS'\
}

mosip.kernel.pdfgenerator.delay-in-millisecond=3000
