# Propiedades del servicio de autorización (idaas)
mosip.ciba.auth.endpoint=https://idaas2.reniec.gob.pe/service/bc-authorize
mosip.ciba.token.endpoint=https://idaas2.reniec.gob.pe/service/ciba/token
mosip.ciba.userinfo.endpoint=https://idaas2.reniec.gob.pe/service/userinfo
